spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jun1980621312
    url: jdbc:mysql://127.0.0.1:3306/miaosha1
mybatis:
  type-aliases-package: com.wjl.springbootmybatis.entity
  mapper-locations: classpath:mappers/*
  #配置rabbitMq 服务器
rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
  #虚拟host 可以不设置,使用server默认host



